AmanNegi/FreshNest

- README.md
> docs: Add Contributors

- README.md
@amitesh-183: issue resolved #21 
- removed contributors from readme.md
> amitesh-183 - removed contributors from readme.md

- frontend/flutter/agro_millets/lib/widgets/custom_text_field.dart
> Added onTapOutside callback to unfocus field[#13]

- frontend/react/README.md
As per issue #23, I have added a README.md file in the "frontend/react" folder.
> #23 Created README.md in "frontend/react" folder

- frontend/react/README.md
Fixed the indentation in the documentation.
> Fixed Indentation in the README.md

- README.md
> Solved #24 issue.

- .github/workflows/build_apk.yml
- Added Workflow to generate APK
> feat: Add APK Generation Workflow

- README.md
> Finally I did it

- README.md
> Solved #47 issue.

- CODE_OF_CONDUCT.md
> Update COC in upstream

- README.md
Hello @AmanNegi 
I'm excited to submit this pull request for review. I've made the following changes to improve the readability of the links:
- Removed code styling
- Made the links bold
Please review and provide your feedback. I'm open to any suggestions or improvements. I'm also happy to make any necessary updates or modifications as needed.
Looking forward to your feedback!
> issue #68: Improve Live Preview Section

- frontend/react/src/pages/shop/presentation/Shop.jsx
> fix: Added Optional Filter Rendering

- backend/index.js
- frontend/react/package-lock.json
- frontend/react/package.json
- frontend/react/src/components/NavBar.jsx
- frontend/react/src/components/ShopItem.jsx
- frontend/react/src/pages/Cart/application/cart.js
- frontend/react/src/pages/Cart/application/cart_event.js
- frontend/react/src/pages/Cart/presentation/Cart.jsx
- frontend/react/src/pages/shop/presentation/Shop.jsx
> feat: Add count indicator in Cart Icon

- frontend/react/src/pages/Search/application/search.js
> fix: Search Error

- frontend/react/src/pages/Search/presentation/Search.jsx
> feat: Add field autofocus in search

- backend/routes/list.js
- frontend/react/package-lock.json
- frontend/react/package.json
- frontend/react/src/index.css
- frontend/react/src/main.jsx
- frontend/react/src/pages/AddItem/application/functions.js
- frontend/react/src/pages/AddItem/presentation/AddItem.jsx
- frontend/react/src/pages/Auth/application/auth.js
- frontend/react/src/pages/Auth/presentation/Login.jsx
- frontend/react/src/pages/Auth/presentation/SignUp.jsx
- frontend/react/src/pages/shop/presentation/Shop.jsx
> feat: Add SignUp Page and AddItem Page

- frontend/react/package-lock.json
- frontend/react/package.json
- frontend/react/src/components/ImageView.jsx
- frontend/react/src/components/NavBar.jsx
- frontend/react/src/components/ShimmerShopItem.jsx
- frontend/react/src/components/ShopItem.jsx
- frontend/react/src/index.css
- frontend/react/src/pages/shop/application/shop.js
- frontend/react/src/pages/shop/presentation/DetailShimmer.jsx
- frontend/react/src/pages/shop/presentation/ItemDetail.jsx
- frontend/react/src/pages/shop/presentation/Shop.jsx
> Fixes: #102 
- Added Shimmer Effect
- Image Parallax Effect added
- Improved basic user-interface
> feat: add shimmer effect (react)

- .vscode/launch.json
- frontend/react/src/components/NavBar.jsx
- frontend/react/src/components/ShopItem.jsx
- frontend/react/src/index.css
- frontend/react/src/pages/Cart/application/cart.js
- frontend/react/src/pages/Cart/presentation/Cart.jsx
- frontend/react/src/pages/Home/presentation/Landing.jsx
- frontend/react/src/pages/Profile/presentation/Profile.jsx
- frontend/react/src/pages/Profile/presentation/UpdateModal.jsx
- frontend/react/src/pages/Search/presentation/Search.jsx
- frontend/react/src/pages/shop/presentation/ItemDetail.jsx
- added typography presets
- added launch script for React
> fix: cart loading issue

- frontend/react/src/pages/shop/presentation/ItemDetail.jsx
Fixed the dollar sign issue and replaced with rupee sign
> Fixed the rupee symbol

- frontend/react/src/data/AppState.js
- frontend/react/src/pages/Profile/presentation/Profile.jsx
issue : #109 
[react.webm](https://github.com/AmanNegi/FreshNest/assets/64489317/21f302ee-6df5-419d-a4ea-524f7b707959)
> feat :Add pattern data to LocalStorage

- frontend/react/src/pages/shop/presentation/ItemDetail.jsx
Fixed Shopitem Mobile layout by increasing height and aligning
> #78 : Fixed ShopItem Mobile Layout

- backend/README.md
- docs/CONTRIBUTING.md
- frontend/flutter/README.md
- frontend/react/README.md
Updated CONTRIBUTING.md with the latest means of running the React frontend locally.
> #115 Updated React Configuration in CONTRIBUTING.md

- CODE_OF_CONDUCT.md
- frontend/react/index.html
<h2>Replace Agro Millets with FreshNest #107</h2>
<h3>Description</h3>
Fix issue #107
> Fixed Issue #107

- frontend/react/src/pages/Auth/presentation/Login.jsx
- frontend/react/src/pages/Auth/presentation/SignUp.jsx
- frontend/react/src/pages/Search/presentation/Search.jsx
Currently, the Google SignUp and Login do not work as expected. This is due to the return type not being destructured properly. This behaviour has been fixed in this PR.
> chore: fix gLogin

- .github/workflows/greetings.yml
Added a basic greeting workflow, which simply greets first time contributors creating issues/PR.
> chore: add greeting workflow

- frontend/react/src/pages/shop/application/shop.js
- frontend/react/src/pages/shop/presentation/Shop.jsx
> Implemented Client-Side Filtering for Shop Page

- frontend/react/package-lock.json
- frontend/react/src/components/ButtonLoader.jsx
- frontend/react/src/pages/Auth/presentation/Login.jsx
- frontend/react/src/pages/Auth/presentation/SignUp.jsx
> Login sign up auth loading

- frontend/react/src/components/Footer.jsx
> dynamic year in footer - react website

- frontend/react/src/pages/Profile/presentation/UpdateModal.jsx
@AmanNegi, please review it, Thank You
fixes  #145 
closes #145
> Add space between phone in dialog box

- frontend/react/src/pages/Auth/application/auth.js
- frontend/react/src/pages/Auth/presentation/Login.jsx
fixed the issue of converting email to lowercase before attempting authorisation
> fix: email uppercase issue

- frontend/react/README.md
hey @AmanNegi , I finished up updating the doc for GLogin Setup in the React Application. Hope it meet the expectations and gets merged up soon. 
Issue in hand:  `[ doc ] : Update .env setup in React Setup Docs` #153 
Ps.: don't forget to mark the PR as `hacktoberfest-accepted`. Have a great day.
> Updated .env for GLogin setup in React Setup Docs

- frontend/flutter/README.md
- frontend/flutter/pubspec.lock
Draft to update the readme file under flutter folder to add steps on how to setup google services config file to get the flutter program running 
solves: https://github.com/AmanNegi/FreshNest/issues/158
> Updating readme for adding google-services file

- frontend/react/src/pages/Auth/presentation/components/GLoginButton.jsx
- frontend/react/src/pages/Auth/presentation/components/PasswordField.jsx
- frontend/react/src/routes.jsx
- Added feature for user to upload images for products.
- Added feature for farmer to upload farm images and form gallery.
- Improved performance by lazy loading pages as necessary.
> feat: add list item page for farmer

- backend/.gitignore
- backend/index.js
- backend/package.json
- backend/src/swagger_output.json
- backend/test/response.js
- backend/test/routes/list.js
- fix scripts
- fix tests
- fix swagger autogen files
> nit: minor fixes

- frontend/react/src/components/NavBar/NavBar.jsx
- frontend/react/src/data/AppState.js
- frontend/react/src/hooks/ProfileHook.js
- frontend/react/src/pages/Cart/application/cart.js
- frontend/react/src/pages/Landing/presentation/Landing.jsx
- frontend/react/src/pages/Profile/application/profile.js
- frontend/react/src/pages/Profile/presentation/Profile.jsx
- frontend/react/src/pages/Profile/presentation/UpdateModal.jsx
- frontend/react/src/pages/shop/application/shop.js
- frontend/react/src/pages/shop/presentation/ItemDetail.jsx
The issue is well-defined in the below comment: 
- https://github.com/AmanNegi/FreshNest/issues/185#issuecomment-1993338341
> fix: react query cache issue

- backend/.gitignore
- backend/src/models/user.js
- backend/src/routes/admin.js
- backend/src/routes/auth.js
- backend/src/routes/cart.js
- backend/src/routes/list.js
- backend/src/routes/profile.js
- backend/src/routes/search.js
- backend/src/startup/db.js
- backend/src/utils/swagger.js
- Update JSDOC comments.
- Update .gitignore to include swagger-output.json
> nit: update .gitignore, update js-doc

- frontend/flutter/lib/core/home/application/home_manager.dart
- frontend/flutter/lib/core/home/presentation/detail/item_detail.dart
- frontend/flutter/lib/core/home/presentation/home_page.dart
- frontend/flutter/lib/core/home/presentation/profile/farm_profile.dart
- frontend/flutter/lib/core/home/presentation/widgets/agro_item.dart
- frontend/flutter/lib/core/home/presentation/widgets/cart_bar.dart
- frontend/flutter/lib/core/map/presentation/map_view.dart
- frontend/flutter/lib/secrets.dart
- User can now see farm reference in product detail and in Map View Page
- Improved Cart Bar UI
> feat: improve cart bar and add farm ref

- frontend/react/.eslintrc.json
- frontend/react/.prettierrc
- frontend/react/src/components/ShopItem.jsx
- frontend/react/src/pages/Profile/application/profile.js
- frontend/react/src/pages/Profile/presentation/FarmerProfile.jsx
- frontend/react/src/pages/Profile/presentation/Profile.jsx
- frontend/react/src/pages/shop/application/shop.js
- frontend/react/src/pages/shop/presentation/ItemDetail.jsx
- frontend/react/src/routes.jsx
- Implements a Farmer Profile page for customers where customers can view the farmer's details, farm images and products.
> feat: add farmer profile for customers
